apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: policy-rag

resources:
  - ../../base

patches:
  - path: backend-patch.yaml
  - path: frontend-patch.yaml
  - path: ingress-patch.yaml

images:
  - name: policy-rag-backend
    newName: ghcr.io/renaldoa/policy-rag-backend
    newTag: latest
  - name: policy-rag-frontend
    newName: ghcr.io/renaldoa/policy-rag-frontend
    newTag: latest
