apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: policy-rag

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - qdrant.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: policy-rag
